export const venues = {
  almeria: {
    name: '?',
    city: 'Almería',
    country: 'Spain',
  },
  asturias: {
    name: '?',
    city: 'Asturias',
    country: 'Spain',
  },
  'birds-nest': {
    name: 'The Birds Nest',
    city: 'London',
    country: 'England',
  },
  blondies: {
    name: 'Blondies',
    borough: 'Clapton',
    city: 'London',
    country: 'England',
  },
  'blondies-brewery': {
    name: 'Blondies Brewery',
    borough: 'Clapton',
    city: 'London',
    country: 'England',
  },
  'calamity-tank': {
    name: 'Calamity Tank',
    borough: 'Leytonstone',
    city: 'London',
    country: 'England',
  },
  'cav-arms-stockwell': {
    name: 'The Cavendish Arms',
    borough: 'Stockwell',
    city: 'London',
    country: 'England',
  },
  'csa-las-vegas': {
    name: 'CSA Las Vegas',
    city: 'Málaga',
    country: 'Spain',
  },
  'damas-lisboa': {
    name: 'Damas',
    city: 'Lisboa',
    country: 'Portugal',
  },
  'down-by-here': {
    name: 'Down By Here',
    city: 'Swansea',
    country: 'Wales',
  },
  'dulwich-dch': {
    name: 'Dulwich Hamlet Clubhouse',
    city: 'London',
    country: 'England',
  },
  'el-perro-perdedor': {
    name: 'El Perro Perdedor',
    city: 'Don Benito',
    country: 'Spain',
  },
  endeavour: {
    name: 'Endeavour',
    borough: 'Deptford',
    city: 'London',
    country: 'England',
  },
  'english-bridge-studios': {
    name: 'English Bridge Studios',
    city: 'Shrewsbury',
    country: 'England',
  },
  'face-bar-reading': {
    name: 'The Face Bar',
    city: 'Reading',
    country: 'England',
  },
  'fla-fla': {
    name: 'Fla Fla',
    city: 'Herford',
    country: 'Germany',
  },
  'grand-burstin-hotel': {
    name: 'The Grand Burstin Hotel',
    city: 'Folkenstone',
    country: 'England',
  },
  helgis: {
    name: `Helgi's`,
    borough: 'Hackney',
    city: 'London',
    country: 'England',
  },
  'high-voltage-bar': {
    name: 'High Voltage Bar',
    city: 'Lille',
    country: 'France',
  },
  'hoffs-margate': {
    name: 'Hoffs',
    city: 'Margate',
    country: 'England',
  },
  'hope-and-anchor': {
    name: 'The Hope & Anchor',
    borough: 'Islington',
    city: 'London',
    country: 'England',
  },
  'ivy-house-nunhead': {
    name: 'The Ivy House',
    borough: 'Nunhead',
    city: 'London',
    country: 'England',
  },
  'jt-soar': {
    name: 'JT Soar',
    city: 'Nottingham',
    country: 'England',
  },
  'la-luna': {
    name: 'La Luna Pub',
    city: 'Elx',
    country: 'Spain',
  },
  madrid: {
    name: '?',
    city: 'Madrid',
    country: 'Spain',
  },
  'muthers-studio': {
    name: 'Muthers Studio',
    city: 'Birmingham',
    country: 'England',
  },
  'new-cross-inn': {
    name: 'New Cross Inn',
    city: 'London',
    country: 'England',
  },
  'new-river-studios': {
    name: 'New River Studios',
    city: 'London',
    country: 'England',
  },
  'planet-sounds': {
    name: 'Planet Sounds',
    city: 'Southampton',
    country: 'England',
  },
  poortgebouw: {
    name: 'Poortgebouw',
    city: 'Rotterdam',
    country: 'Netherlands',
  },
  porto: {
    name: '?',
    city: 'Porto',
    country: 'Portugal',
  },
  privat: {
    name: 'Privat',
    city: 'Cologne',
    country: 'Germany',
  },
  'red-lion-leytonstone': {
    name: 'The Red Lion',
    borough: 'Leytonstone',
    city: 'London',
    country: 'England',
  },
  'sala-fantastica': {
    name: 'Sala Fantástica',
    city: 'Santiago de Compostela',
    country: 'Spain',
  },
  'sala-la-trinchera': {
    name: 'Sala La Trinchera',
    city: 'Madrid',
    country: 'Spain',
  },
  'signature-brew-hag': {
    name: 'Signature Brew',
    borough: 'Haggerston',
    city: 'London',
    country: 'England',
  },
  'the-holloway': {
    name: 'The Holloway',
    city: 'Norwich',
    country: 'England',
  },
  'the-old-spotted-dog-ground': {
    name: 'The Old Spotted Dog Groud',
    borough: 'Clapton',
    city: 'London',
    country: 'England',
  },
  'the-pump-trowbridge': {
    name: 'The Pump',
    city: 'Trowbridge',
    country: 'England',
  },
  'the-star-inn-ashford': {
    name: 'The Star Inn',
    city: 'Ashford',
    country: 'England',
  },
  'the-victoria': {
    name: 'The Victoria',
    borough: 'Dalston',
    city: 'London',
    country: 'England',
  },
  'two-palms': {
    name: 'Two Palms',
    borough: 'Hackney',
    city: 'London',
    country: 'England',
  },
  'walthamstow-trades-hall': {
    name: 'Walthamstow Trades Hall',
    borough: 'Walthamstow',
    city: 'London',
    country: 'England',
  },
  'zaguan-almeria': {
    name: 'Zaguán',
    city: 'Almería',
    country: 'Spain',
  },
};
